# {**/  double check render.yaml for proper configuration **/}

services:
  - type: web
    name: kanban
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001

# {**/  matches the Postgres connection string: postgresql://kanban_user:q0vQDd0KrXJdUKQQg0VwoGD2QzwSTzfY@dpg-cuip2atumphs73dshtb0-a/kanban_db_ngpw **/}

databases:
  - name: kanban-db
    region: ohio
    plan: free
    databaseName: kanban_db
    user: kanban_user
    ipAllowList: []

# {**/ Hostname: dpg-cuip2atumphs73dshtb0-a **/}

# {**/ Port: 5432 **/}

# {**/ Database: kanban_db_ngpw **/}

# {**/ Username: kanban_user **/}

# {**/ Password: q0vQDd0KrXJdUKQQg0VwoGD2QzwSTzfY **/}
