services:
  - type: web
    name: kanban
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001

databases:
  - name: kanban-db
    region: ohio
    plan: free
    databaseName: kanban_db
    user: kanban_user
    ipAllowList: []
