
services:
  - type: web
    name: kanban-board
    runtime: node
    plan: standard
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
        sync: false
      - key: PORT
        value: 3001
